name: 'Build & Deploy'
on: 
  push: 
    branches: 
      - 'develop'
  workflow_dispatch: 
jobs:
  build: 
    name: 'Build & Publish'
    runs-on: ubuntu-latest
    steps: 
      - name: 'Checkout repository'
        uses: actions/checkout@v3
      
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v2
      
      - name: 'Login to GitHub Registry'
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          
      - name: 'Build & Deploy API Gateway'
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Storage.API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/develop/storage-microservice-api
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'Install SSH Key'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_TOKEN }}

            docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/develop/storage-microservice-api:latest

            docker stop storage-api-microservice

            docker rm storage-api-microservice

            cd ./docker
            
            docker compose -f docker-compose-develop.yaml up storage-api-microservice -d --build
